name: BE deploy staging
run-name: BE deploy staging
on:
  push:
    branches:
      - master
    paths:
      - backend/**
defaults:
  run:
    working-directory: ./backend
jobs:
  build:
    runs-on: [self-hosted, backend-server-stagging]
    steps:
      - name: before checkout
        run: ls
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          ls

          echo 'build'
