name: BE deploy staging
run-name: BE deploy staging
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: Nhập branch/tags muốn build, default dùng dev rồi
        default: dev
defaults:
  run:
    working-directory: ./backend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: check out
         uses: actions/checkout@v2
         with:
          persist-credentials: false
          ref: ${{ github.event.inputs.version }}
       - name: hienthi
         run: |
          echo ${{ github.actor }}
          echo  ${{ github.event.inputs.version }}
